# Check if the number is an Armstrong number or not...?

In [3]:
n = int(input("Enter a integer value:"))
sum = 0
temp = n
while temp>0:
    dig = temp % 10
    sum += dig **3
    temp //= 10

if sum == n:
    print("The number is armstrong number")
else:
    print("It is not a armstrong number")

Enter a integer value:153
The number is armstrong number


# Write a function called show_stars(rows). If rows are 5, it should print the following
#  *
#  **
#  ***
#  ****
#  *****

In [5]:
m = int(input("Enter an integer:"))
for i in range(0,m):
    for j in range(0, i+1):
        print("*", end='')
    print("\r")

Enter an integer:5
*
**
***
****
*****


# Write a program to remove characters from a string starting from zero up to n and return a new string...?  

In [13]:
str_1 = str(input("Enter string values"))
print ("The original string is : " + str_1)
n = int(input("Enter the position of the string to remove"))
new_str = str_1[:(n-1)] +  str_1[n:]
print ("The string after removal of i'th character : " + new_str)

Enter string values123456789
The original string is : 123456789
Enter the position of the string to remove9
The string after removal of i'th character : 12345678


# Iterate the given list of numbers and print only those numbers which are divisible by 5..?

In [1]:
x = []
n_1 = int(input("Enter no. of list elements"))
for i in range(n_1):
    x_1 = int(input())
    x.append(x_1)
x_2 = []
def div_5(x):
   print("Given list",x)
   for i in x:
       if i%5 == 0:
          x_2.append(i)
div_5(x)
print("The list is",x_2)

Enter no. of list elements5
1
5
15
13
20
Given list [1, 5, 15, 13, 20]
The list is [5, 15, 20]


# Print the following pattern
# 1
# 22
# 333
# 4444
# 55555

In [1]:
rows = 6
for i in range(rows):
    for j in range(i):
        print(i, end=' ')
    print('')



1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


#   Write a program to check if the given number is a palindrome number

In [3]:
n_3 = int(input("Enter number:"))
temp = n_3
rev = 0 
while(n_3>0):
    dig = n_3 %10
    rev = rev*10+dig
    n_3 = n_3//10
if(temp == rev):
    print("The number is a palindrome!")
else:
    print("The number isn't a palindrome!")

Enter number:121
The number is a palindrome!


# Python program to interchange first and last elements in a list

In [6]:
def swapList(newList):
    size = len(newList)
    temp_1 = newList[0]
    newList[0] = newList[size - 1]
    newList[size - 1] = temp_1
    return newList

n_4 = int(input("Enter an integer :"))
newList = []
for i in range(n_4):
    c = int(input())
    newList.append(c)
print(swapList(newList))

Enter an integer :5
1
2
3
4
5
[5, 2, 3, 4, 1]


#  

# Python program to swap two elements in a list

In [4]:
def swapPositions(list, pos1, pos2):
     
    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list

List = []
n_5 = int(input("Enter no of array elements :"))
for i in range(n_5):
    n_6 = int(input())
    List.append(n_6)
pos1, pos2  = 1, 3
 
print(swapPositions(List, pos1-1, pos2-1))

Enter no of array elements :5
1
2
3
4
5
[3, 2, 1, 4, 5]


# Ways to find length of list

In [5]:
List = []
n_5 = int(input("Enter no of array elements :"))
for i in range(n_5):
    n_6 = int(input())
    List.append(n_6)
len(List)

Enter no of array elements :5
1
2
3
4
5


5

# Maximum of two numbers in Python

In [6]:
a=[]
n=int(input("Enter number of elements:"))
for i in range(1,n+1):
    b=int(input("Enter element:"))
    a.append(b)
a.sort()
print("First largest element is:",a[n-1])
print("Second largest element is:",a[n-2])

Enter number of elements:5
Enter element:23
Enter element:12
Enter element:43
Enter element:54
Enter element:67
First largest element is: 67
Second largest element is: 54


# Minimum of two numbers in Python

In [8]:
a=[]
n=int(input("Enter number of elements:"))
for i in range(1,n+1):
    b=int(input("Enter element:"))
    a.append(b)
a.sort()
print("The smallest element is:",a[n-(n-1)])
print("Second smallest element is:",a[n-(n-2)])

Enter number of elements:5
Enter element:12
Enter element:13
Enter element:14
Enter element:15
Enter element:16
The smallest element is: 13
Second smallest element is: 14


#  Python program to check whether the string is Symmetrical or Palindrome

In [9]:
string = 'amaama'
half = int(len(string) / 2)
 
if len(string) % 2 == 0:  
    first_str = string[:half]
    second_str = string[half:]
else:
    first_str = string[:half]
    second_str = string[half+1:]

if first_str == second_str:
    print(string, 'string is symmertical')
else:
    print(string, 'string is not symmertical')
 
if first_str == second_str[::-1]:  
    print(string, 'string is palindrome')
else:
    print(string, 'string is not palindrome')

amaama string is symmertical
amaama string is palindrome


#  Reverse words in a given String in Python

In [10]:
string = str(input("Enter a string value :"))
s = string.split()[::-1]
l = []
for i in s:
    l.append(i)
print(" ".join(l))


Enter a string value :harish is a good boy
boy good a is harish


#   Ways to remove i’th character from string in Python

In [1]:
test_str = "python interpreter"
print ("The original string is : " + test_str)
z = str(input("Which character you want to remove ?"))
new_str = test_str.replace(z, '', 1)
print ("The string after removal of i'th character(works) : " + new_str)

The original string is : python interpreter
Which character you want to remove ?y
The string after removal of i'th character(works) : pthon interpreter


#  Python program to Find the size of a Tuple

In [16]:
import sys
tuple_1 = ("A", 1, "B", 2, "C", 3)
print("The first tuple is :")
print(tuple_1)
print("Size of first tuple is : " + str(sys.getsizeof(tuple_1)) + " bytes")

The first tuple is :
('A', 1, 'B', 2, 'C', 3)
Size of first tuple is : 88 bytes


#   Python – Maximum and Minimum K elements in Tuple

In [19]:
def Findel(tup,K):
    result = []
    test_tup = list(tup)
    temp = sorted(tup)
    for i, val in enumerate(temp):
        if i < K or i >= len(temp) - K:
            result.append(val)
    result = tuple(result)
    # printing result 
    print("Max and Min K elements : ",result)

tup = (13, 10, 23, 2, 5, 6, 12)
K = int(input("Enter an integer"))
print("The original tuple: ", tup)
Findel(tup,K)

Enter an integer1
The original tuple:  (13, 10, 23, 2, 5, 6, 12)
Max and Min K elements :  (2, 23)


# Python | Sort Python Dictionaries by Key or Value

In [2]:
def diction():
    key = {}
    key[2] = 23
    key[1] = 78
    key[5] = 56
    key[6] = 295
    key[10] = 27
    print("key", key)
    print("keys and values sorted")
 
    for i in sorted(key):
        print((i, key[i]), end=" ")
def main():
    diction()
if __name__ == "__main__":
    main()


key {2: 23, 1: 78, 5: 56, 6: 295, 10: 27}
keys and values sorted
(1, 78) (2, 23) (5, 56) (6, 295) (10, 27) 

#  Python dictionary with keys having multiple inputs

In [3]:
my_dict = {}
a, b, c = 50, 126, 80
my_dict[a, b, c] = a + b - c
a, b, c = 52, 54, 11
my_dict[a, b, c] = a + b - c
print("The dictionary are :")
print(my_dict)

The dictionary are :
{(50, 126, 80): 96, (52, 54, 11): 95}


#  Find the size of a Set in Python

In [5]:
import sys
Set_1 = {"Apple", 1, "Ball", 2, "Cat", 3}
Set_2 = {"Harish", "Suba", "Aravindh", "Shastee", "Abi", "Kohli"}
Set_3 = {(1, "Star"), ( 2, "Day"), (3, "Night")}
  
print("Size of Set1: " + str(sys.getsizeof(Set_1)) + "bytes")
print("Size of Set2: " + str(sys.getsizeof(Set_2)) + "bytes")
print("Size of Set3: " + str(sys.getsizeof(Set_3)) + "bytes")

Size of Set1: 472bytes
Size of Set2: 472bytes
Size of Set3: 216bytes


#  Iterate over a set in Python

In [7]:
test_set = set("HARISH")
for val in test_set:
    print(val)

A
R
S
I
H


#  Assigning subsequent rows to matrix first row element

In [8]:
my_list=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print("my list :"+str(my_list))
result={my_list[0][val] : my_list[val+1] for val in range(len(my_list)-1)}
print("The matrix : " +str(result))

my list :[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
The matrix : {1: [4, 5, 6], 2: [7, 8, 9], 3: [10, 11, 12]}


#  Adding and Subtracting Matrices in Python

In [9]:
import numpy as np
A = np.array([[10,5],[9,9]])
B = np.array([[4,4],[5,6]])
print("elments in A")
print(A)
print("elments in B")
print(B)
print("addition of two matrix")
print(np.add(A,B))
print("subtraction of two matrics")
print(np.subtract(A,B))

elments in A
[[10  5]
 [ 9  9]]
elments in B
[[4 4]
 [5 6]]
addition of two matrix
[[14  9]
 [14 15]]
subtraction of two matrics
[[6 1]
 [4 3]]


#  how to get list of parameter name from a function in python

In [10]:
def fun(a, b, c):
    return a**b**c
import inspect
print(inspect.signature(fun))

(a, b, c)


#  how to Print Multiple Arguments in Python?

In [13]:
def books(player_name, sports):
    print("SPORTS DETAILS : " , player_name + ' - ' + sports)
books("Virat Kohli" , "Cricket")
books("Sunil Chetri" , "Foot Ball")
books("Saina Nehwal" , "Badminton")

SPORTS DETAILS :  Virat Kohli - Cricket
SPORTS DETAILS :  Sunil Chetri - Foot Ball
SPORTS DETAILS :  Saina Nehwal - Badminton
